/* 
**  mod_tcpfingerprint.c -- Apache sample tcpfingerprint module
**  [Autogenerated via ``apxs -n tcpfingerprint -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_tcpfingerprint.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /tcpfingerprint in as follows:
**
**    #   apache2.conf
**    LoadModule tcpfingerprint_module modules/mod_tcpfingerprint.so
**    <Location /tcpfingerprint>
**    SetHandler tcpfingerprint
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /tcpfingerprint and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/tcpfingerprint 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_tcpfingerprint.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_connection.h"
#include "http_log.h"
#include "apr_strings.h"
#include "http_request.h"
#include "ap_listen.h"
#include "apr_lib.h"

#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/ip6.h>
#include <netinet/tcp.h>


extern module AP_MODULE_DECLARE_DATA tcpfingerprint_module;


typedef struct
{
    const char *pkt_data;
    int pkt_len;
    const struct iphdr *ip;
    const struct ip6_hdr *ip6;
    const struct tcphdr *tcp;
    int tcp_offset;
    int ip_version;
} syn_packet_t;

typedef struct
{
    const struct tcp_info *tcp_info;
    syn_packet_t *saved_syn;
    //TODO: add timestamp to allow calcuation of TLS_HELLO_DELAY
} fingerprint_data_t;



static int parse_pkt(syn_packet_t *syn)
{
    int ip6_offset = sizeof(struct ip6_hdr);
    struct ip6_ext *ext;
    
    if (syn->ip_version > 0 || syn->ip_version == -1)
    {
        return syn->ip_version;
    }
    syn->ip_version = (((unsigned char) syn->pkt_data[0]) & 0xF0) >> 4;
    
    
    if (syn->ip_version == 4)
    {
        syn->ip = (struct iphdr *)syn->pkt_data;
        syn->tcp_offset = syn->ip->ihl * 4;
    }
    
    if (syn->ip_version == 6)
    {
        syn->ip6 = (struct ip6_hdr *)syn->pkt_data;
        if (syn->ip6->ip6_nxt == IPPROTO_TCP)
        {
            syn->tcp_offset = ip6_offset;
        } else
        {
            ext = (struct ip6_ext *)(&(syn->pkt_data[ip6_offset]));
            while (ip6_offset < syn->pkt_len - 8)
            {
                ip6_offset += (ext->ip6e_len + 1) * 8;
                if (ext->ip6e_nxt == IPPROTO_TCP)
                {
                    syn->tcp_offset = ip6_offset;
                } else
                {
                    ext = (struct ip6_ext *)(&(syn->pkt_data[ip6_offset]));
                } 
            }
        }
    }
    
    if (!(syn->ip_version == 4 || syn->ip_version == 6))
    {
        syn->ip_version = -1;
        syn->tcp_offset = 0;
    }

    if (syn->tcp_offset > 0)
    {
        if (syn->tcp_offset <= syn->pkt_len - 20)
        {
            syn->tcp = (struct tcphdr *)(&(syn->pkt_data[syn->tcp_offset]));
        } else
        {
            syn->ip_version = -1;
        }
    }
    
    return syn->ip_version;
}



static int fingerprint_post_config(apr_pool_t *pconf, apr_pool_t *plog, apr_pool_t *ptemp, server_rec *s)
{
    //set save_syn on all listeners
    ap_listen_rec *lr;
    int listen_sd;
    int res;
    int save_syn = 1;
    apr_status_t stat = 0;

    for(lr = ap_listeners; lr; lr = lr->next) 
    {
        //if (lr->bind_addr)
        //{
        //    ap_log_error(APLOG_MARK, APLOG_ERR, 0, s, "listen port: %i", (int) lr->bind_addr->port);
        //}
        apr_os_sock_get(&listen_sd, lr->sd);
        res = setsockopt(listen_sd, IPPROTO_TCP, TCP_SAVE_SYN, &save_syn, sizeof(save_syn));
        if (res < 0)
        {
            stat = apr_get_netos_error();
            ap_log_error(APLOG_MARK, APLOG_ERR, stat, s, "Failed to set TCP_SAVE_SYN on listener for port: %i", (int) lr->bind_addr->port);
        } else
        {

            ap_log_error(APLOG_MARK, APLOG_ERR, 0, s, "set TCP_SAVE_SYN on listener for port: %i", (int) lr->bind_addr->port);
        }   
    }

    //set callback for customlog
    return OK; 

}


static int fingerprint_pre_connection(conn_rec *c, void *csd)
{
    ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "pre_connection");

    fingerprint_data_t *data = NULL;
    struct tcp_info ti;
    int ti_length = 0;
    int res = 0;
    apr_status_t stat = 0;
    int sd = 0;
    int nonblock = 0;
    char syn_packet[196];
    int syn_length = 96;
    
    
    apr_os_sock_get(&sd, csd);

    //only add fingerprint into to master connection, if this is a slave connection, do nothing.
    if (!c->master)
    {
        data = apr_pcalloc(c->pool, sizeof(*data));
        ap_set_module_config(c->conn_config, &tcpfingerprint_module, data);

        ti_length = sizeof(ti);
        //ti = apr_pcalloc(c->pool, ti_length);

        //syn_packet = apr_pcalloc(c->pool, syn_length);
                
        stat = apr_socket_opt_get(csd, APR_SO_NONBLOCK, &nonblock);
        if (stat != APR_SUCCESS)
        {
            ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to get socket nonblock status");
        }

        if (nonblock)
        {
            stat = apr_socket_opt_set(csd, APR_SO_NONBLOCK, 0);
            if (stat != APR_SUCCESS)
            {
                ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to temporarily disable socket nonblock");
            }
        }


        res = getsockopt(sd, IPPROTO_TCP, TCP_INFO, &ti, (socklen_t *)&ti_length);
        if (res < 0)
        {
            stat = apr_get_netos_error();
            ap_log_cerror(APLOG_MARK, APLOG_ERR, stat, c, "error getting TCP_INFO");

        } else
        {
            //check ti len?
            data->tcp_info = apr_pmemdup(c->pool, &ti, ti_length);
            ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "TCP_INFO stored for connection");
        }

        res = getsockopt(sd, IPPROTO_TCP, TCP_SAVED_SYN, &syn_packet, (socklen_t *)&syn_length);
        if (res < 0)
        {
            stat = apr_get_netos_error();
            ap_log_cerror(APLOG_MARK, APLOG_ERR, stat, c, "error getting TCP_SAVED_SYN");

        } else
        {
            data->saved_syn = apr_pcalloc(c->pool, sizeof(syn_packet_t));
            data->saved_syn->pkt_data = apr_pmemdup(c->pool, &syn_packet, syn_length);
            data->saved_syn->pkt_len = syn_length;
            ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "TCP_SAVED_SYN stored for connection");
        }



        if (nonblock)
        {
            stat = apr_socket_opt_set(csd, APR_SO_NONBLOCK, 1);
            if (stat != APR_SUCCESS)
            {
                ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to re-enable socket nonblock");
            }
        }

    }
    return OK;
}

static int fingerprint_fixups(request_rec* r)
{
    conn_rec *c = r->connection;
    fingerprint_data_t *data = NULL;

    char *name= NULL;
    char *value = NULL;

    
    //always use master connection?
    if (c->master)
    {
        c = c->master;
    }
    
    data = (fingerprint_data_t *) ap_get_module_config(c->conn_config, &tcpfingerprint_module);
    
    if (data)
    {
        if (data->tcp_info)
        {
            name = apr_psprintf(r->pool, "%s", "TCP_RTT");
            value = apr_psprintf(r->pool, "%lu", (unsigned long) data->tcp_info->tcpi_rtt);
            apr_table_setn(r->subprocess_env, name, value);
        }
        if (data->saved_syn && (parse_pkt(data->saved_syn) > 0))
        {
            name = apr_psprintf(r->pool, "%s", "TCP_OFFSET");
            value = apr_psprintf(r->pool, "%i", data->saved_syn->tcp_offset);
            apr_table_setn(r->subprocess_env, name, value);
        }
    }

    return OK;

}


static void tcpfingerprint_register_hooks(apr_pool_t *p)
{
    //ap_hook_handler(tcpfingerprint_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_post_config(fingerprint_post_config, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_pre_connection(fingerprint_pre_connection, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_fixups(fingerprint_fixups, NULL, NULL, APR_HOOK_REALLY_FIRST);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA tcpfingerprint_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    tcpfingerprint_register_hooks  /* register hooks                      */
};


