/* 
**  mod_tcpfingerprint.c -- Apache sample tcpfingerprint module
**  [Autogenerated via ``apxs -n tcpfingerprint -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_tcpfingerprint.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /tcpfingerprint in as follows:
**
**    #   apache2.conf
**    LoadModule tcpfingerprint_module modules/mod_tcpfingerprint.so
**    <Location /tcpfingerprint>
**    SetHandler tcpfingerprint
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /tcpfingerprint and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/tcpfingerprint 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_tcpfingerprint.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_connection.h"
#include "http_log.h"


#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>


extern module AP_MODULE_DECLARE_DATA tcpfingerprint_module;


typedef struct {
    const struct tcp_info *tcp_info;
} fingerprint_data_t;



static int fingerprint_pre_connection(conn_rec *c, void *csd)
{
    ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "pre_connection");

    fingerprint_data_t *data = NULL;
    struct tcp_info *ti = NULL;
    int ti_length = 0;
    int res = 0;
    apr_status_t stat = 0;
    int sd = 0;
    int nonblock = 0;
    
    apr_os_sock_get(&sd, csd);

    //only add fingerprint into to master connection, if this is a slave connection, do nothing.
    if (!c->master)
    {
        data = apr_pcalloc(c->pool, sizeof(*data));
        ap_set_module_config(c->conn_config, &tcpfingerprint_module, data);

        ti_length = sizeof(*ti);
        ti = apr_pcalloc(c->pool, ti_length);
                
        stat = apr_socket_opt_get(csd, APR_SO_NONBLOCK, &nonblock);
        if (stat != APR_SUCCESS)
        {
            ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to get socket nonblock status");
        }

        if (nonblock)
        {
            stat = apr_socket_opt_set(csd, APR_SO_NONBLOCK, 0);
            if (stat != APR_SUCCESS)
            {
                ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to temporarily disable socket nonblock");
            }
        }


        res = getsockopt(sd, IPPROTO_TCP, TCP_INFO, ti, (socklen_t *)&ti_length);
        if (res < 0)
        {
            stat = apr_get_netos_error();
            ap_log_cerror(APLOG_MARK, APLOG_ERR, stat, c, "error getting TCP_INFO");

        } else
        {
            //check ti len?
            data->tcp_info = ti;
            ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "TCP_INFO stored for connection");
        }

        if (nonblock)
        {
            stat = apr_socket_opt_set(csd, APR_SO_NONBLOCK, 1);
            if (stat != APR_SUCCESS)
            {
                ap_log_cerror(APLOG_MARK, APLOG_ERR, 0, c, "Failed to re-enable socket nonblock");
            }
        }

    }
    return OK;
}


static void tcpfingerprint_register_hooks(apr_pool_t *p)
{
    //ap_hook_handler(tcpfingerprint_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_pre_connection(fingerprint_pre_connection, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA tcpfingerprint_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    tcpfingerprint_register_hooks  /* register hooks                      */
};

